name: pos_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.0
  flutter_animate: ^4.5.2
  mobile_scanner: ^7.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^9.0.0
  pdf: ^3.10.10
  printing: ^5.13.0
  path_provider: ^2.1.5
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  fl_chart: ^0.71.0
  esc_pos_utils_plus: ^2.0.3
  blue_thermal_printer: ^1.2.3
  audioplayers: ^6.1.0
  vibration: ^2.0.1
  tutorial_coach_mark: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
